from __future__ import annotations

import unittest

from types import SimpleNamespace

from specification.generated import a2a_pb2
from tck.requirements.core_operations import CORE_OPERATIONS_REQUIREMENTS
from tests.compatibility.core_operations.test_requirements import _validate_response


class ContextIdTest(unittest.TestCase):
    """Cover context-ID outcomes missing from the conditional requirement tests."""

    def setUp(self) -> None:
        """Use the context ID generated by the requirement registry."""
        self.requirement = next(r for r in CORE_OPERATIONS_REQUIREMENTS if r.id == "CORE-MULTI-002a")
        self.context_id = self.requirement.sample_input["message"]["contextId"]

    def test_grpc_accepts_preserved_context_in_task_and_message(self) -> None:
        """Either protobuf oneof member can carry the accepted context."""
        for payload in (
            a2a_pb2.SendMessageResponse(task=a2a_pb2.Task(context_id=self.context_id)),
            a2a_pb2.SendMessageResponse(message=a2a_pb2.Message(context_id=self.context_id)),
        ):
            with self.subTest(payload=payload):
                response = SimpleNamespace(success=True, raw_response=payload)
                self.assertEqual([], _validate_response(response, "grpc", self.requirement, {}))

    def test_grpc_rejects_replaced_or_missing_context(self) -> None:
        """Successful responses must preserve the requested context."""
        for payload in (
            a2a_pb2.SendMessageResponse(task=a2a_pb2.Task(context_id="replaced")),
            a2a_pb2.SendMessageResponse(message=a2a_pb2.Message(context_id="replaced")),
            a2a_pb2.SendMessageResponse(task=a2a_pb2.Task()),
            a2a_pb2.SendMessageResponse(message=a2a_pb2.Message()),
            a2a_pb2.SendMessageResponse(),
        ):
            with self.subTest(payload=payload):
                response = SimpleNamespace(success=True, raw_response=payload)
                self.assertTrue(_validate_response(response, "grpc", self.requirement, {}))

    def test_transport_failure_does_not_count_as_context_rejection(self) -> None:
        """A connection failure without an error code is not a server rejection."""
        for transport in ("grpc", "jsonrpc", "http_json"):
            with self.subTest(transport=transport):
                response = SimpleNamespace(
                    success=False, error="Connection refused", error_code=None, raw_response=None,
                )
                self.assertTrue(_validate_response(response, transport, self.requirement, {}))


if __name__ == "__main__":
    unittest.main(verbosity=2)
